# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4561c9f1773a48863132c0c9e451b90002e4515f268a16136fc3bc4581272cb0acdc52d8baf718cbdd769f5a77ec6137ac9b69b56788cd441be454678e542955

test:
  secret_key_base: 948a53df472d222dd8dd4a692cf00815a95edde93914f7c3359520270cda234e3788e0edbbc498222b21e238fb46868450320f0d77222a8a91f6122bd9aa5819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
